USE bookstore;
CREATE TABLE IF NOT EXISTS Cartbook (
  CartId INT NOT NULL,
  BookId INT NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CartId, BookId),
  FOREIGN KEY (CartId) REFERENCES Cart(id),
  FOREIGN KEY (BookId) REFERENCES Book(id)
);
CREATE TABLE IF NOT EXISTS Checkout (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  addressLine1 VARCHAR(255) NOT NULL,
  addressLine2 VARCHAR(255) NOT NULL,
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  zipCode VARCHAR(255) NOT NULL,
  subTotal DECIMAL(13,2) NOT NULL,
  CartId INT NOT NULL UNIQUE,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (CartId) REFERENCES Cart(id)
);
