variable "project_name" {
  type        = string
  description = "Unique lab resource prefix."
  default     = "eze-favour-epicbook"
  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{2,30}[a-z0-9]$", var.project_name))
    error_message = "Use 4-32 lowercase letters, digits or hyphens, starting with a letter and ending alphanumeric."
  }
}

variable "aws_region" {
  type        = string
  description = "Explicit commercial AWS Region, re-confirmed after authorization."
  validation {
    condition     = can(regex("^(us|eu|ap|ca|sa|af|me|il|mx)-[a-z]+-[0-9]+$", var.aws_region))
    error_message = "Provide a commercial AWS Region, not an account, URL or placeholder."
  }
}

variable "availability_zones" {
  type        = list(string)
  description = "Two distinct AZs in aws_region; availability must be checked in the authorized account."
  validation {
    condition     = length(var.availability_zones) == 2 && length(distinct(var.availability_zones)) == 2 && alltrue([for az in var.availability_zones : can(regex("^[a-z]{2}-[a-z]+-[0-9]+[a-z]$", az)) && startswith(az, var.aws_region)])
    error_message = "Provide exactly two distinct AZs in the selected Region."
  }
}

variable "controller_cidr" {
  type        = string
  description = "Explicit controller public IPv4 /32; never 0.0.0.0/0 or a private address."
  validation {
    condition     = can(cidrnetmask(var.controller_cidr)) && endswith(var.controller_cidr, "/32") && !can(regex("^(0[.]|10[.]|127[.]|169[.]254[.]|172[.](1[6-9]|2[0-9]|3[01])[.]|192[.]168[.]|100[.](6[4-9]|[7-9][0-9]|1[01][0-9]|12[0-7])[.]|198[.](18|19)[.]|22[4-9][.]|2[3-5][0-9][.])", var.controller_cidr))
    error_message = "SSH requires an explicit public IPv4 /32 (not private, loopback, link-local, shared, multicast or unrestricted)."
  }
}

variable "key_name" {
  type        = string
  description = "Existing EC2 key pair name in the approved account/Region; no keys are generated by this project."
  validation {
    condition     = can(regex("^[A-Za-z0-9][A-Za-z0-9._-]{0,254}$", var.key_name))
    error_message = "Use an existing key pair name, not a path or key material."
  }
}

variable "ec2_instance_type" {
  type        = string
  default     = "t3.micro"
  description = "Small x86_64 lab instance; billable and subject to regional availability."
  validation {
    condition     = contains(["t3.micro", "t3.small"], var.ec2_instance_type)
    error_message = "Use t3.micro or t3.small; review costs before increasing capacity."
  }
}

variable "db_instance_class" {
  type        = string
  default     = "db.t3.micro"
  description = "Single-AZ lab RDS class; confirm MySQL 8.4 orderability and price before any plan."
  validation {
    condition     = contains(["db.t3.micro", "db.t3.small"], var.db_instance_class)
    error_message = "Use db.t3.micro or db.t3.small after a price/availability review."
  }
}

variable "mysql_version" {
  type        = string
  default     = "8.4"
  description = "Supported MySQL 8.4 LTS line; select an available minor during the authorized review. Runtime compatibility is pending."
  validation {
    condition     = can(regex("^8\\.4(\\.[0-9]+)?$", var.mysql_version))
    error_message = "This lab targets MySQL 8.4 LTS, not obsolete MySQL 5.7."
  }
}

variable "db_username" {
  type        = string
  sensitive   = true
  description = "RDS master username. Sensitive, but AWS stores this non-write-only field in Terraform state."
  validation {
    condition     = can(regex("^[a-zA-Z][a-zA-Z0-9]{0,15}$", var.db_username)) && !contains(["admin", "root", "mysql", "rdsadmin", "epicbookapp"], lower(var.db_username))
    error_message = "Use 1-16 alphanumeric characters starting with a letter; avoid reserved usernames, including epicbookapp."
  }
}

variable "db_password" {
  type        = string
  sensitive   = true
  ephemeral   = true
  description = "Supply interactively via TF_VAR_db_password; used only by write-only RDS and runtime-secret fields."
  validation {
    condition     = can(regex("^[A-Za-z0-9!#%^*+=_-]{24,64}$", var.db_password))
    error_message = "Use a unique 24-64 character password from letters, numbers and !#%^*+=_- (no whitespace or quotes)."
  }
}

variable "credential_version" {
  type        = number
  default     = 1
  description = "Increment when rotating the supplied password; updates both write-only fields and replaces EC2 bootstrap."
  validation {
    condition     = var.credential_version >= 1 && floor(var.credential_version) == var.credential_version
    error_message = "Use a positive integer credential version."
  }
}

variable "accept_lab_data_loss" {
  type        = bool
  description = "Must explicitly accept disposable lab data: no automated backups/final snapshot, immediate secret deletion on destroy."
  validation {
    condition     = var.accept_lab_data_loss
    error_message = "Explicitly accept lab data loss only after the human budget/cleanup gate."
  }
}
